Dct type 1
icl-utk-edu/heffte pull request #26
Opened 2023-06-28 15:48 UTC by vmontanaro

-Added namespace for DCT-I in cufft
-Added prepost processing kernels
-Added additional normalization factor
-Added test case in `test_cosine_transform.cpp`

2023-06-28 16:32 UTC, mkstoyanov commented
@G-Ragghianti Hey, I think the container or spack in the CI need updating. Thanks!

2023-06-29 15:05 UTC, G-Ragghianti commented
I updated the gpu_intel runner to include all the required modules, but it is still having problems on the ONEAPI and gpu_intel runs.  The gpu_nvidia run is due to OOM error and is unrelated.

2023-06-30 13:19 UTC, vmontanaro commented
> I updated the gpu_intel runner to include all the required modules, but it is still having problems on the ONEAPI and gpu_intel runs. The gpu_nvidia run is due to OOM error and is unrelated.



> @G-Ragghianti Hey, I think the container or spack in the CI need updating. Thanks!

Resolved with the latest push. Somehow i forgot to ` git add` the files for ONEAPI and ROCFFT...

2023-06-30 18:30 UTC, mkstoyanov requested changes
We need a better way to do the factor.

2023-07-03 19:50 UTC, mkstoyanov requested changes
Almost there.

2023-07-03 19:50 UTC, mkstoyanov commented on include/heffte_fft3d.h
> +            else if(std::is_same<backend_tag, heffte::backend::cufft_cos1>::value) {
There shouldn't be a new line here.

2023-07-03 19:50 UTC, mkstoyanov commented on include/heffte_r2r_executor.h
> +box3d<index> make_cos_box(box3d<index> const &box, int factor){
The `make_cos_box()` method isn't used anymore. We an just remove it.

2023-07-03 19:50 UTC, mkstoyanov commented on include/heffte_r2r_executor.h
> +    static box3d<index> make_extended_box(box3d<index> const &box){
This looks much better, but now we a common pattern that can be extracted into a separate method, as opposed to copy-paste. Namely, let's make `make_extended_box` into a separate template method, and let's make a new name to it.
```
template<typename prepost_processor, typename index>
box3d<index> make_extended_r2r_box(box3d<index> const &box){
    std::array<index, 3> high{box.size[0]-1, box.size[1]-1, box.size[2]-1};
    high[box.order[0]] = prepost_processor::compute_extended_length(box.osize(0)) - 1;
    return box3d<index>(std::array<index, 3>{0, 0, 0}, high, box.order);
}
```

2023-07-03 19:50 UTC, mkstoyanov commented on include/heffte_r2r_executor.h
> +        fft(make_executor_r2c<fft_backend_tag>(stream, prepost_processor::make_extended_box(box), dimension))
Using the new extended box, this will become
```
fft(make_executor_r2c<fft_backend_tag>(stream, make_extended_r2r_box<prepost_processor>(box), dimension))
```

2023-07-04 14:18 UTC, vmontanaro commented on include/heffte_r2r_executor.h
> +    static box3d<index> make_extended_box(box3d<index> const &box){
Makes sense! i'll do it then.

2023-07-05 15:54 UTC, mkstoyanov commented on test/test_cos.cpp
> +        tassert(approx(inverse, reference_inv, (std::is_same<scalar_type, float>::value) ? 0.001 : 1.0));
I'm approving the PR but this is an important point. What changed in this line is the addition of a blank space.

I always set my code-editors to remove trailing spaces, this is important to avoid pollution to the git-history. For example, if we later find a problem on this line and we are trying to see how we got here, according to git, you're the last person to make changes here, even though you did not really change anything.

Next time I make any changes to this file, my editor will remove the space and it will look like I added one more change here ... but nothing changed.

2023-07-05 15:54 UTC, mkstoyanov approved these changes

2023-07-05 16:13 UTC, vmontanaro commented on test/test_cos.cpp
> +        tassert(approx(inverse, reference_inv, (std::is_same<scalar_type, float>::value) ? 0.001 : 1.0));
Oh, thanks. I didn't notice, i should change my VSCode settings.

2023-07-05 19:17 UTC, merged