[Draft] Fix CMake: FFTW Threads
icl-utk-edu/heffte pull request #55
Opened 2024-08-29 00:42 UTC by ax3l

Trying to fix build issues on Linux in Conda-Forge in which pthreads are over-linked and ill-resolved from FFTW: https://github.com/conda-forge/staged-recipes/pull/26633

:warning: Please don't merge yet. :warning:

2024-08-29 03:46 UTC, ax3l commented on cmake/FindHeffteFFTW.cmake
> +        list(APPEND FFTW_LIBRARIES "${FFTW_OMP_LIBRARIES}")
That was a bug for OMP.

2024-08-29 16:08 UTC, ax3l commented
@mkstoyanov this one is ready for review now :)

2024-08-30 07:13 UTC, mkstoyanov requested changes

2024-08-30 07:13 UTC, mkstoyanov commented on cmake/FindHeffteFFTW.cmake
> +    if (FFTW_THREADS_LIBRARIES)
The current way of listing all libraries will favor searching for OpenMP over Threads. I think we should preserve this behavior, e.g., search for OpenMP first and then look for threads only if the OpenMP libraries were not found.

The main reason is that scientific code using OpenMP is far more common than Threads.

2024-08-30 07:13 UTC, mkstoyanov commented on cmake/FindHeffteFFTW.cmake
> +        if(WIN32)  # Windows has an internal pthreads lib we can use
heFFTe doesn't support windows, I don't even know how one will start with MPI on Windows.

2024-08-30 07:13 UTC, mkstoyanov commented on cmake/HeffteConfig.cmake
> +        if(WIN32)  # Windows has an internal pthreads lib we can use
Same, no need to consider windows.

2024-08-30 07:15 UTC, mkstoyanov commented
@ax3l I'm currently on vacation, so I'm responding with a delay.

I don't like changing the default behavior on system with both threads and openmp, which should be an easy fix.

I also don't like superfluous code for features that aren't supported anyway. But other than that, this looks OK.

2024-08-30 07:44 UTC, ax3l commented on cmake/FindHeffteFFTW.cmake
> +    if (FFTW_THREADS_LIBRARIES)
Makes sense to me, will update tomorrow

2024-10-23 23:58 UTC, mkstoyanov commented
Effectively done in #65

2024-10-23 23:58 UTC, closed without merging